openapi: 3.0.4
info:
  title: Random Data Generator
  description: >-
    Random Generator is a simple tool for generating random data. It returns
    random data such as numbers, strings, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/randomgenerator:
    get:
      summary: Generate Random Data
      description: Generate random data of various types
      operationId: randomgenerator
      parameters:
        - name: type
          in: query
          schema:
            type: string
          required: true
          description: The type of random data to generate
          example: number
        - name: count
          in: query
          schema:
            type: integer
          required: false
          description: The number of random data to generate (1 to 100)
          example: 10
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  type: phone
                  count: 10
                  data:
                    - 967-950-4587
                    - 792-611-7468 x1293
                    - (933) 311-9829
                    - 389.357.7403 x793
                    - 1-621-490-6394
                    - 1-699-562-6833 x8558
                    - 875.226.1530 x641
                    - 744-991-0150 x1974
                    - 1-393-784-0533 x15199
                    - 954-876-6958 x0398
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
